#! /bin/bash

# Copyright (c) 2013 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# script to implement changes to the app to target crosswalk

cp manifest.json src/
